### ISSUE TITLE
ClassCastException: Response cannot be cast to ObjectResponse

### ISSUE THREAD

**Issue by romanstrobl** [lime-company/powerauth-push-server#52]
java.lang.ClassCastException: io.getlime.core.rest.model.base.response.Response cannot be cast to io.getlime.core.rest.model.base.response.ObjectResponse
	at io.getlime.push.client.PushServerClient.checkStatus(PushServerClient.java:440) ~[powerauth-push-client-0.17.0.jar:0.17.0]
	at io.getlime.push.client.PushServerClient.postObjectImpl(PushServerClient.java:407) ~[powerauth-push-client-0.17.0.jar:0.17.0]
	at io.getlime.push.client.PushServerClient.createDevice(PushServerClient.java:145) ~[powerauth-push-client-0.17.0.jar:0.17.0]
	at io.getlime.security.powerauth.lib.webflow.authentication.mtoken.controller.MobileAppApiController.registerDevice(MobileAppApiController.java:109) ~[powerauth-webflow-authentication-mtoken-0.15.0.jar!/:0.15.0]

**Comment by petrdvorak** [comment]
Probably invalid, caused by the fact lib was not installed in Maven.
